name: "Build .Net"

on:
  push:
    branches: [ "main" ]
    paths: [ "src/dotnet" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "src/dotnet" ]

jobs:
  build-test-job:
    runs-on: ubuntu-latest
    env:
      workdir: "./src/dotnet"

    steps:
    - uses: actions/checkout@v3

    - name: Setup .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ${{env.workdir}}
      run: dotnet restore

    - name: Build
      working-directory: ${{env.workdir}}
      run: dotnet build --no-restore
